name: Build on macOS
on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: InstalI Docker
        run: |
          brew update
          brew install docker
      - name: Install Coolify
        run: |
          docker pull ubuntu
          docker run -it ubuntu
          curl -fsSL https://cdn.coollabs.io/coolify/install.sh | sudo bash
